// Generated by CoffeeScript 2.5.1
(function() {
  var connectAssets, teacup;

  connectAssets = require('connect-assets');

  teacup = require('..');

  // Returns connect-assets middleware and
  // binds teacup.js and teacup.css to connect-assets helpers

  // express = require 'express'
  // connectAssets = require 'teacup/connect-assets'
  // app = express()
  // app.configure ->
  //   app.use connectAssets(src: 'assets',
  //           jsDir: 'javascripts', cssDir: 'stylesheets')
  module.exports = function(options = {}) {
    var connectMiddleware, helperContext, raw, renderable;
    // Create helper context, pass it to connect-assets, and reset js & css roots
    options.helperContext = helperContext = {};
    connectMiddleware = connectAssets(options);
    if (options.jsDir != null) {
      helperContext.js.root = options.jsDir;
    }
    if (options.cssDir != null) {
      helperContext.css.root = options.cssDir;
    }
    // Bind js & css helpers to teacup
    ({renderable, raw} = teacup);
    teacup.js = renderable(function(path, options) {
      return raw(helperContext.js(path, options));
    });
    teacup.css = renderable(function(path, options) {
      return raw(helperContext.css(path, options));
    });
    return connectMiddleware;
  };

}).call(this);
