// Generated by CoffeeScript 1.8.0
(function() {
  var CoffeeScript;

  CoffeeScript = require('coffee-script/register');

  module.exports = {
    renderFile: function(path, options, callback) {
      var err;
      try {
        if ((options.app != null) && !options.app.enabled('view cache')) {
          delete require.cache[require.resolve(path)];
        }
        return callback(null, require(path)(options));
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
