// Generated by CoffeeScript 1.6.1
(function() {
  var CoffeeScript;

  CoffeeScript = require('coffee-script');

  module.exports = {
    renderFile: function(path, options, callback) {
      try {
        if ((options.app != null) && !options.app.enabled('view cache')) {
          delete require.cache[require.resolve(path)];
        }
        return callback(null, require(path)(options));
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
